FROM node:18 as git_stage

WORKDIR /app
RUN apt-get update && apt-get install -y git && apt-get purge -y --auto-remove  && rm -rf /var/lib/apt/lists/*
ARG GIT_TAG="v0.0.1"
RUN git clone --branch v0.0.1 --single-branch https://github.com/mimunzar/mapstitcher.git

########################################################################################

FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DEBIAN_FRONTEND=noninteractive

# dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    libopenjp2-tools \
    git \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

# mapstitcher
WORKDIR /app/mapstitcher

COPY --from=git_stage app/mapstitcher/requirements.txt ./requirements.txt
RUN pip install -r requirements.txt

COPY --from=git_stage app/mapstitcher ./
COPY entrypoint_oneshot.sh /app/entrypoint_oneshot.sh
COPY entrypoint_service.sh /app/entrypoint_service.sh
RUN chmod +x /app/entrypoint_oneshot.sh /app/entrypoint_service.sh

# run
CMD ["python3", "image_stitch_batch.py", "--path", "/data/", "--output", "/data/stitched.jp2"]
